on: [push]

name: Build

env:
  GIT_AUTHOR_NAME: actions
  GIT_AUTHOR_EMAIL: wjessen@thefarmersdog.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: master
          FOLDER: docs
